models:
  - type: main
    engine: openai
    model: gpt-4.1-mini
    parameters:
      temperature: 0.0

rails:
  input:
    flows:
      - self check input

  output:
    flows:
      - self check output